os: linux
dist: bionic 
language: minimal 
sudo: true 
install: 
 - ./setup-wp.sh
 - sleep 1
#script: curl example.com | grep testing
script: 
 - curl example.com 
 - sudo cat /var/log/nginx/error.log 
